
af=%11%acompressor
audio-normalize-downmix=%3%yes
audio-pitch-correction=%3%yes
autofit-larger=%7%40%x40%
autofit-smaller=%7%30%x30%
correct-downscaling=%3%yes
cscale=%16%ewa_lanczossharp
deband=%3%yes
deband-iterations=%1%4
dither-depth=%4%auto
force-window=%3%yes
geometry=%7%30%:30%
gpu-api=%6%vulkan
hwdec=%5%vaapi
keep-open=%3%yes
linear-downscaling=%3%yes
osc=%2%no
osd-font=%14%JetBrains Mono
osd-font-size=%2%28
profile=%6%gpu-hq
save-position-on-quit=%3%yes
scale=%16%ewa_lanczossharp
screenshot-directory=%22%~/Pictures/Screenshots
screenshot-format=%3%png
screenshot-png-compression=%1%4
screenshot-tag-colorspace=%3%yes
sigmoid-upscaling=%3%yes
sub-ass-override=%5%force
sub-auto=%5%fuzzy
sub-border-color=%7%#000000
sub-border-size=%1%2
sub-color=%7%#FFFFFF
sub-font=%14%JetBrains Mono
sub-font-size=%2%42
sub-shadow-color=%7%#000000
sub-shadow-offset=%1%2
vo=%8%gpu-next
volume=%3%100
volume-max=%3%150
ytdl-format=%52%bestvideo[height<=1080]+bestaudio/best[height<=1080]


